const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..", "..");
const api = fs.readFileSync(path.join(root, "functions", "src", "api.ts"), "utf8");
const index = fs.readFileSync(path.join(root, "functions", "src", "index.ts"), "utf8");
const tasks = fs.readFileSync(path.join(root, "functions", "src", "tasks.ts"), "utf8");
const weekly = fs.readFileSync(path.join(root, "functions", "src", "weekly.ts"), "utf8");
const worker = fs.readFileSync(path.join(root, "firebase", "worker.py"), "utf8");
const fetcher = fs.readFileSync(path.join(root, "src", "moneymaker", "fetcher.py"), "utf8");
const deploy = fs.readFileSync(path.join(root, "scripts", "deploy_firebase_native.ps1"), "utf8");

assert.match(api, /async function resumeFailedRefreshTracking/);
assert.match(api, /parameters_json->>'history_end_date'/);
assert.match(api, /parameters_json->>'force_full_history'/);
assert.match(api, /started_at_utc > NOW\(\) - INTERVAL '48 hours'/);
assert.match(api, /WHERE refresh_job_id = \$1 AND status = 'failed'/);
assert.match(api, /result_json = COALESCE\(result_json, '\{\}'::jsonb\) - 'cloud_run_dispatch'/);
assert.match(api, /SET status = 'running', stage = 'Fetching batches'/);
assert.match(api, /started_at_utc < NOW\(\) - INTERVAL '6 hours'/);
assert.match(api, /active\.attempts > 0/);
assert.match(api, /status = 'running'\n\s*AND started_at_utc < NOW\(\) - INTERVAL '45 minutes'/);
assert.match(api, /updated_at_utc < NOW\(\) - INTERVAL '45 minutes'/);
assert.match(api, /failed_parent_batches AS/);
assert.match(api, /NOT \(fj\.parameters_json \? 'refresh_batch_id'\)/);
assert.match(api, /rb\.refresh_job_id::text = fj\.parameters_json ->> 'refresh_job_id'/);
assert.match(api, /failed_parent_refreshes AS/);
assert.match(index, /export \{scheduledJobReconciliation, scheduledRatingOutcomes\} from "\.\/scheduled"/);
assert.match(deploy, /"scheduledweeklypublication"/);
assert.match(deploy, /"scheduleddatabaseidleshutdown"/);
assert.match(deploy, /"scheduledjobreconciliation"/);
assert.doesNotMatch(deploy, /"scheduledrefreshasx"/);
assert.doesNotMatch(deploy, /"scheduledrefreshus"/);
assert.doesNotMatch(deploy, /"scheduleddefaultscanasx"/);
assert.doesNotMatch(deploy, /"scheduleddefaultscanus"/);
assert.match(deploy, /"scheduledratingoutcomes"/);
assert.match(weekly, /us_refresh_retry_count/);
assert.match(weekly, /retryCount < maxRetries\[retryKey\]/);

assert.match(tasks, /WHERE id = \$1 AND refresh_job_id = \$2 AND status <> 'succeeded'/);
assert.match(tasks, /const status = await childFetchStatus\(existingChildJobId\)/);
assert.match(tasks, /if \(\["queued", "running"\]\.includes\(status\)\)/);
assert.match(tasks, /const jobId = crypto\.randomUUID\(\)/);

assert.match(worker, /def reconcile_refresh_job/);
assert.match(worker, /finished_at_utc = COALESCE\(%s, finished_at_utc\),\n\s*updated_at_utc = now\(\)/);
assert.match(worker, /def staging_checkpoint_path/);
assert.match(worker, /def main\(\) -> int:/);
assert.match(worker, /incremental_mode = not force_full_history/);
assert.doesNotMatch(worker, /incremental_mode = not batch_refresh/);
assert.match(worker, /cache = staging_checkpoint_path\(market\) if incremental_mode else checkpoint_path\(market\)/);
assert.match(worker, /if not batch_refresh and force_full_history:\n\s*upload_checkpoint\(market, cache\)/);
assert.match(worker, /if incremental_mode:\s*\r?\n\s*# Incremental parent and task-queue batch refreshes must not pull/);
assert.match(worker, /FILTER \(WHERE status = 'succeeded'\)/);
assert.match(worker, /FILTER \(WHERE status = 'failed'\)/);
assert.doesNotMatch(worker, /completed_tickers = completed_tickers \+/);
assert.doesNotMatch(worker, /failed_tickers = failed_tickers \+/);
assert.match(worker, /WHERE id = %s AND refresh_job_id = %s AND status <> 'succeeded'/);
assert.match(worker, /SELECT ticker, MAX\(price_date\)/);
assert.match(worker, /AND price_date < %s::date/);
assert.match(worker, /latest_price_dates\[ticker\] - timedelta\(days=history_overlap_days\)/);
assert.match(worker, /history_start_overrides=history_start_overrides/);
assert.match(worker, /seeded_company_count = fetcher\.seed_info_cache/);
assert.match(worker, /counts\["fetch_mode"\] = "full_history" if force_full_history else "incremental"/);
assert.match(worker, /counts\["missing_history_count"\] = len\(missing_histories\)/);
assert.match(worker, /INSERT INTO fetch_errors/);
assert.match(worker, /partial rows were saved and the batch is safe to retry/);
assert.match(worker, /return 0\n\s*except Exception as exc:/);
assert.match(worker, /return 1\n\n\nif __name__ == "__main__":/);
assert.match(worker, /exit_code = main\(\)/);
assert.match(worker, /sys\.stdout\.flush\(\)\n\s*sys\.stderr\.flush\(\)/);
assert.match(worker, /os\._exit\(exit_code\)/);
assert.match(worker, /non-daemon threads alive/);
assert.match(fetcher, /start_overrides: Optional\[Mapping\[str, object\]\]/);
assert.match(fetcher, /fetch_start = max\(requested_start, _coerce_date\(override\)\)/);
assert.match(fetcher, /def seed_info_cache/);
assert.match(fetcher, /metadata_output: Optional\[Dict\[str, object\]\]/);
assert.match(fetcher, /retry_data, retry_failures, retry_stopped = _download_chunk_sequential/);

console.log("fetch resilience tests passed");
